#!/bin/bash
# My first script

# REMOVE ALL THE OLD TRC FILES ------------------------------------------------
rm *.trc
#------------------------------------------------------------------------------

# REMOVE THE OLD EXECUTABLE ---------------------------------------------------
rm pas
#------------------------------------------------------------------------------

# REMOVE THE OLD FILE CREATED BY LEX ------------------------------------------
rm paslex.cpp
#------------------------------------------------------------------------------

# CALL THE MAKE FILE TO COMPILE IT ALL TOGETHER -------------------------------
make -f makepascal
#------------------------------------------------------------------------------

# REMOVE THE OBJECT FILES AFTER COMPILATION THE KEEP THE DIR DECLUTERED -------
rm pas.o
rm paslex.o
#------------------------------------------------------------------------------

#CALL FOR TESTING -------------------------------------------------------------
echo T01
./pas t01.pas
echo T02
./pas t02.pas
echo T03
./pas t03.pas
echo T04
./pas t04.pas
echo T05
./pas t05.pas
#./pas BadInputFile.wro
#------------------------------------------------------------------------------