#ifndef paspar_h
#define paspar_h 1
//--------------------------------------------------------------------
// File paspar.h defines the interface to the parser generated by
// yacc.
//--------------------------------------------------------------------
// Author: Thomas R. Turner                                           
// E-Mail: trturner.ucok.edu                                          
// Date:   August, 2005                                              
//--------------------------------------------------------------------
// Copyright August, 2005 by Thomas R. Turner
// Do not reproduce without permission from Thomas R. Turner.
//--------------------------------------------------------------------
//Application include files
//--------------------------------------------------------------------
#include "paslex.h"
//--------------------------------------------------------------------
//--------------------------------------------------------------------
//Function yyparse is the parser generated by yacc.                  
//--------------------------------------------------------------------
#ifdef __cplusplus
extern "C" 
#endif
int yyparse (void);
#endif
class Parser : public Lexer {
public:
  Parser(FILE* i):Lexer(i){}
  int Parse(void) { return yyparse(); }
};
